### ISSUE TITLE
java.net.BindException: Permission denied

### ISSUE THREAD

**Issue by tired9494** [granny/Pl3xMap-test#10]
https://paste.ubuntu.com/p/7rdkhbDD2w/ (the last ~30 lines)

I edited the config so that `web-address` is set to `http://localhost:80` and `port` is set to `80`. I don't have any web servers running so port 80 should be free. 

Port `80` is allowed in my firewall.

Not sure what else to try.

**Comment by YouHaveTrouble** [comment]
Only root-level services can open ports below 1024. You should make it listen to another higher port. If you want portless domain, you need to reverse proxy it to the desired port.

**Comment by tired9494** [comment]
Ah alright, the wiki might benefit from that info as a note, as it says simply says the port can be assigned to `80`

**Comment by EvilOlaf** [comment]
> Ah alright, the wiki might benefit from that info as a note, as it says simply says the port can be assigned to 80

Agreed. Novice users might bump into this.

Search:
`You can set it to port 80 if no other services are using it, which will allow users to use the map without specifying a port in the address bar.`

Replace with something like:
```
Having port-less access to your map (without specifying the port like :8080 in the browsers' address bar to say) requires additional setup on the host machine and/or firewall rules.
If that is not an option you might be able to create a firewall rule that simply forwards all traffic hitting port 80 to 8080 on your machine.
If that is not an option either there is another non-option because it is actually a very, very bad idea since it tremendously increases security risks: So please DO NOT run your Minecraft server as root user! (no, seriously, don't do it!)

Best practice solution is setting up a reverse proxy.
```

**Comment by granny** [comment]
Slightly updated the wiki to be a bit more clear.
