### ISSUE TITLE
If using nginx as reverse proxy/server, biome and Y coordinate display are broken (showing either ??? or unknown)

### ISSUE THREAD

**Issue by melzyy** [granny/Pl3xMap-test#13]
![image](https://github.com/granny/Pl3xMap/assets/71926357/cdbca375-672b-422b-8f34-fe593943121d)

**Comment by Roan-V** [comment]
You need to tell nginx how to handle a few filetypes that are compressed by Pl3xmap
Basically just need to set the content encoding for a specific filetype

Instructions and code snippet here: 
https://github.com/granny/Pl3xMap/wiki/Internal%2C-External-and-Reverse-Proxy-Web-Servers

**Comment by melzyy** [comment]
> You need to tell nginx how to handle a few filetypes that are compressed by Pl3xmap Basically just need to set the content encoding for a specific filetype
> 
> Instructions and code snippet here: https://github.com/granny/Pl3xMap/wiki/Internal%2C-External-and-Reverse-Proxy-Web-Servers

The problem is that ive already done that, but maybe im missing something 

![image](https://github.com/granny/Pl3xMap/assets/71926357/caa05c55-bf76-40fa-98ab-3e73a7a9d4fa)
here is my nginx cfg, only the map part

**Comment by granny** [comment]
Please join the discord server for support. https://granny.dev/discord

**Comment by melzyy** [comment]
for anyone from google, i fixed it by removing ^ from from locaton line

**Comment by granny** [comment]
Already updated in the wiki
