### ISSUE TITLE
Pl3xMapEnabledEvent only running sometimes

### ISSUE THREAD

**Issue by gjorgdy** [granny/Pl3xMap-test#22]
No logs or errors to go along with it, why I'm coming here.
I'm using the following code, but it only seems to run 1/3 times.

`Pl3xMap.api().getEventRegistry().register(new Pl3xMapStart());`

`@EventHandler
public void onEnable(Pl3xMapEnabledEvent event) {
}`

**Comment by granny** [comment]
i'm going to need more code to understand your issue. Give me an example plugin where you can recreate the problem.

**Comment by gjorgdy** [comment]
Got this working, I registered the event too late. I'll make a new issue for the actual problem that led me to this.
