### ISSUE TITLE
Pl3xMapEnabledEvent gets called too early

### ISSUE THREAD

**Issue by gjorgdy** [granny/Pl3xMap-test#23]
I'm trying to load in markers on start with this event, but when the event is called. The WorldRegistry (`Pl3xMap.api().getWorldRegistry()`) is still empty. Meaning I can't make a layer and thus not register markers.

Main class;
```java
@Override
public void onInitializeServer() {
	ServerLifecycleEvents.SERVER_STARTING.register(server -> {
		SERVER = server;
		Pl3xMap.api().getEventRegistry().register(new Pl3xMapStart());
	});
}
```

Event;
```java
private static class Pl3xMapStart implements EventListener {
	@EventHandler
	public void onEnable(Pl3xMapEnabledEvent event) {
			// initialize manager
			MARKER_MANAGER.loadLodestones(); // this creates markers and tries to register them
		}
	}
}```

**Comment by granny** [comment]
[WorldLoadedEvent](https://granny.github.io/Pl3xMap/net/pl3x/map/core/event/world/WorldLoadedEvent.html) and [WorldUnloadedEvent](https://granny.github.io/Pl3xMap/net/pl3x/map/core/event/world/WorldUnloadedEvent.html) Pl3xMap events exist for this reason. You can register/unregister your layers through those events.
