### ISSUE TITLE
Single point markers

### ISSUE THREAD

**Issue by zbigniewcebula** [granny/Pl3xMap-test#26]
No info about creating markers that are single point

**Comment by jedrek0429** [comment]
Is this issue about examples in the wiki?

**Comment by jedrek0429** [comment]
Resolved with [`68002d4`](https://github.com/granny/Pl3xMap/wiki/Custom-Markers/68002d42df1277a4c4db0faa8ded8bdd24596b80) wiki revision.

**Comment by zbigniewcebula** [comment]
Thanks!
