### ISSUE TITLE
MySQL support (multiserver)

### ISSUE THREAD

**Issue by Nans-ssss** [granny/Pl3xMap-test#29]
Hi! I use two servers with the plugin, I don't think it's possible to link them? (With SQL)
Here's an example:

![image](https://github.com/granny/Pl3xMap/assets/146657048/278e0827-5f0d-48d6-b13c-11e42c1b7d21)

Below the overworld, put nether and end (which are on my other server).

Thanks !

**Comment by granny** [comment]
No plans on using any database for this. You'll have to use a custom frontend like [LiveAtlas](https://github.com/JLyne/LiveAtlas).
