### ISSUE TITLE
Random lag spikes with Pl3xMap errors

### ISSUE THREAD

**Issue by Crystal-Spider** [granny/Pl3xMap-test#37]
My server usually runs well, and the online map does too.  
However, randomly, I get some Pl3xMap errors and lag spikes.  
Below is the link for the relevant portion of a log (from when the lag starts to when the lag ends).
[2024-04-06.log](https://mclo.gs/TXTkspu)

**Comment by granny** [comment]
Should be fixed as of https://github.com/granny/Pl3xMap/commit/74054345190d5a660af87332e6a69c64480547b2
