### ISSUE TITLE
Deprecated com.destroystokyo.paper.event.brigadier.CommandRegisteredEvent warning

### ISSUE THREAD

**Issue by MoiraPrime** [granny/Pl3xMap-test#41]
On startup I get the following error in my console.

`[Pl3xMap]: "Pl3xMap v1.20.6-494" has registered a listener for com.destroystokyo.paper.event.brigadier.CommandRegisteredEvent on method "public void org.incendo.cloud.paper.PaperBrigadierListener.onCommandRegister(com.destroystokyo.paper.event.brigadier.CommandRegisteredEvent<com.destroystokyo.paper.brigadier.BukkitBrigadierCommandSource>)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [granny, BillyGalbreath, JLyne].`

**Comment by granny** [comment]
I don't see the notice using the latest version of Pl3xMap (`v1.21.4-516`). Let me know if it continues to show up for you.
