### ISSUE TITLE
Not showing online players

### ISSUE THREAD

**Issue by jemcdevitt** [granny/Pl3xMap-test#43]
Started new 1.20.6 server, running Spigot and plugin version Pl3xMap-1.20.6-495.jar.  The map is rendering beautifully but it shows no players on line and no player icons.  Checked configurations and player layer is set to show them.

**Comment by granny** [comment]
Join my discord server for support: https://granny.dev/discord

**Comment by Dragonissa** [comment]
So how is this issue going to be fixed?

**Comment by granny** [comment]
Make sure you're using the latest 1.20.6 build. If it's still not working then

> Join my discord server for support: https://granny.dev/discord

**Comment by Dragonissa** [comment]
i've used the latest and it definitely didn't worked. No errors whatsoever.

![image](https://github.com/granny/Pl3xMap/assets/4233773/82d0bdc0-9075-4151-b47b-b36e893ee5c5)

**Comment by granny** [comment]
> Join my discord server for support: https://granny.dev/discord
