### ISSUE TITLE
web map rendering problem.

### ISSUE THREAD

**Issue by myut0** [granny/Pl3xMap-test#47]
mods im using: pl3xmap, jjthunder to the max.
issue: not sure how to explain but it looks like some weird artifacts of some sort. can see them in the screenshot.
![image](https://github.com/granny/Pl3xMap/assets/135757948/2bf9be04-7585-457a-af7e-dd8f5a240930)

ingame generation of the world looks normal and doesnt have those lines.

**Comment by BillyGalbreath** [comment]
![alt](https://media2.giphy.com/media/v1.Y2lkPTc5MGI3NjExeXE5d2VyY245YmVmMXBtdm93ZXJwN2ZieGp6c3RvMXJwYTU5d2R6ZyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/3oKGzhms9ZvdlqGGJ2/giphy.webp)

**Comment by granny** [comment]
Seems like that's just how it's meant to look with the rendering type & heightmap type you have selected. I'd recommend playing around with the different heightmap options and seeing what looks best.

If you need any additional help, feel free to join the discord for more support: [granny.dev/discord](https://granny.dev/discord)
