### ISSUE TITLE
Suggestion - Add Custom Skin URL/ Skin Restorer Support

### ISSUE THREAD

**Issue by LichLord91** [granny/Pl3xMap-test#57]
I haven't used Pl3xmap yet but I do have dynmap/squaremap and want to switch over to pl3x.

 However one thing that's stopping me is perhaps the lack of skinrestorer/custom skin url?

This may be built in and I'm wasting your time but I know squaremap has at least the custom skin url addon and not direct skinrestorer support like Dynmap does. 

Anyway we can get this added as a feature if it does not exist? 

https://github.com/jpenilla/squaremap-addons/tree/master/addons/skins

https://skinsrestorer.net/

**Comment by BillyGalbreath** [comment]
It's built-in to Pl3xMap v3. Back in Pl3xMap v1 days it required an addon. squaremap is just a fork of Pl3xMap v1 which is why it requires an addon, too ;)
