### ISSUE TITLE
Missing texture: tuff bricks

### ISSUE THREAD

**Issue by Skilon72** [granny/Pl3xMap-test#58]
Tuff bricks are not being displayed on the web map.

![no tuff bricks](https://github.com/user-attachments/assets/19238cf7-9b3e-443f-bde5-2f3760d437af)

Image explanation:
The border you can see is the grass blocks that got turned into dirt because of the tuff bricks on top of them.
The space between that border should all be tuff bricks (but it's grass)

**Comment by granny** [comment]
Implemented in 7321d939db8c5b0af187995f5fb0757fa71e872c

Please regenerate your `colors.yml` to allow the new values to show up in the file.
