### ISSUE TITLE
Pl3xMap is spamming requests, like a INSANE amount. (Skin Spam/Request Spam)

### ISSUE THREAD

**Issue by Xeravax** [granny/Pl3xMap-test#67]
![chrome_x3qWYAlkqe](https://github.com/user-attachments/assets/db1d2003-9f36-4503-be2a-3ed3c9db3471)
![chrome_gDaGFgAMG0](https://github.com/user-attachments/assets/29ac99e8-5b85-4f44-99f7-f537ae192adb)

**Comment by granny** [comment]
Just had a chance to look into this. Since you have inspect element open I'm assuming you have `Disable cache` selected. If you deselect it then the browser should respect the image caching and stop spamming requests.

**Comment by Xeravax** [comment]
> Just had a chance to look into this. Since you have inspect element open I'm assuming you have `Disable cache` selected. If you deselect it then the browser should respect the image caching and stop spamming requests.

This happens for EVERY player on the server when they open the map, not when using inspect element.

**Comment by Askarionn** [comment]
bump
