### ISSUE TITLE
Copper grates render inconsistently based on oxidation

### ISSUE THREAD

**Issue by MoiraPrime** [granny/Pl3xMap-test#68]
Reporting an inconsistency I just noticed. I have a bridge composed of copper grates. 

Copper grates (waxed and unwaxed) are transparent, so anything underneath them is rendered instead.

Exposed copper grates are not treated as transparent and render on the map

Weathered copper grates are treated as transparent and don't render on the map.

I'm not sure how oxidized copper grates are treated as I don't have any currently.... but either way these should probably all be treated consistently.

![image](https://github.com/user-attachments/assets/2c2c08bc-f84b-4a49-a7c9-08c3f42e06c0)

Edit: Plugin version is Pl3xMap-1.21.3-510

**Comment by granny** [comment]
Please regenerate your `colors.yml` to allow the new values to show up in the file.
