### ISSUE TITLE
Spigot 1.21.4 / Pl3xMap-1.21.4-512 - ServerCrash when Webmap is opened

### ISSUE THREAD

**Issue by wofnull** [granny/Pl3xMap-test#71]
Hi there,

during the upgrade process of our server to the most current version of the itself, we tested all Plugins due to stability / servercrash issues and found when Spigot Version 1.21.4 is loaded together with Pl3xMap-1.21.4-512 ( Modrinth Download for Spigot ) the server works fine until the map gets opened. The server then crashes directly and reboots itself.

After deactivating the plugin, the problem was solved.

Logfile is attached ( Pl3xmap was opened 16:53:50 ):

[2024-12-07-13.log](https://github.com/user-attachments/files/18049097/2024-12-07-13.log)

**Comment by granny** [comment]
In that log you shared it looks like watchdog activated after you ran the `save-all` command. When you run that command on spigot, it immediately begins writing all chunk data that's stored in cache into the world files. Please don't run that command if Pl3xMap is in the middle of a render.

**Comment by granny** [comment]
Please join the discord server for future support requests. https://granny.dev/discord
