### ISSUE TITLE
Pale Garden blocks do not render

### ISSUE THREAD

**Issue by MoiraPrime** [granny/Pl3xMap-test#73]
Noticing on 1.21.4 that Pale Oak leaves, Pale Oak Logs, and Pale Moss do not render on the map.

![image](https://github.com/user-attachments/assets/c190cd14-fe99-47ad-bfef-d38cbfd3b464)

Version: 1.21.4-512

**Comment by granny** [comment]
Please regenerate your `colors.yml` to allow the new values to show up in the file.
